# Docker Compose 통합 실행 파일
# 
# 이 파일은 기본적으로 인프라 서비스와 애플리케이션을 함께 실행합니다.
# 
# 사용법:
# - 전체 실행: docker-compose up -d
# - 인프라만 실행: docker-compose -f docker-compose.infra.yml up -d
# - 앱만 실행: docker-compose -f docker-compose.app.yml up -d
# - 다중 파일 실행: docker-compose -f docker-compose.infra.yml -f docker-compose.app.yml up -d

version: '3.8'

services:
  # MariaDB 데이터베이스
  mariadb:
    extends:
      file: docker-compose.infra.yml
      service: mariadb

  # Redis 캐시 서버
  redis:
    extends:
      file: docker-compose.infra.yml
      service: redis

  # Zookeeper (Kafka 의존성)
  zookeeper:
    extends:
      file: docker-compose.infra.yml
      service: zookeeper

  # Kafka 메시지 브로커
  kafka:
    extends:
      file: docker-compose.infra.yml
      service: kafka

  # Kafka UI (선택사항 - 개발 시 유용)
  kafka-ui:
    extends:
      file: docker-compose.infra.yml
      service: kafka-ui

  # Spring Boot 애플리케이션
  customer-api:
    extends:
      file: docker-compose.app.yml
      service: customer-api
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

# 볼륨 정의
volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
  kafka_data:
    driver: local

# 네트워크 정의
networks:
  customer-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16