# Production Profile - MariaDB
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/commerce_prod?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:commerce_user}
    password: ${DB_PASSWORD:commerce_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    com.commerce: INFO